blank_issues_enabled: true
contact_links:
  - name: Discord Channel
    url: http://discord.opencollective.com
    about: Engage with the Open Collective community
  - name: Documentation
    url: https://docs.opencollective.com/help/
    about: Documentation for Open Collective
  - name: Security Policy
    url: https://github.com/opencollective/opencollective/security/policy
    about: Please report security vulnerabilities as outlined here
